# Generated by Django 5.2.7 on 2025-11-04 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0003_activity_expected_result_alter_activity_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activity",
            old_name="date",
            new_name="delivery_date",
        ),
        migrations.RenameField(
            model_name="activity",
            old_name="expected_result",
            new_name="expected_grade",
        ),
        migrations.RenameField(
            model_name="activity",
            old_name="result",
            new_name="grade_result",
        ),
        migrations.RenameField(
            model_name="activity",
            old_name="weight",
            new_name="grade_weight",
        ),
    ]
