# Generated by Django 5.2.7 on 2025-10-25 10:23

import environment
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_alter_course_options_alter_course_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(blank=True, default=environment.get_timezone),
        ),
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
