# Generated by Django 5.2.7 on 2025-11-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_course_created_at_course_updated_at"),
        ("institution", "0008_institution_unique_institution_user_name"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(
                fields=("name", "instituition"), name="unique_course_institution"
            ),
        ),
    ]
