# Generated by Django 5.2.7 on 2025-11-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_course_unique_course_institution"),
        ("institution", "0008_institution_unique_institution_user_name"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="course",
            name="unique_course_institution",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="instituition",
            new_name="institution",
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(
                fields=("name", "institution"), name="unique_course_institution"
            ),
        ),
    ]
