# Generated by Django 5.2.7 on 2025-11-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0005_remove_course_unique_course_institution_and_more"),
        ("institution", "0008_institution_unique_institution_user_name"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="course",
            name="unique_course_institution",
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(
                fields=("name", "acronym", "institution"),
                name="unique_course_institution",
            ),
        ),
    ]
