# Generated by Django 5.2.7 on 2025-10-25 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_created_at_user_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="senha",
            new_name="password",
        ),
    ]
