# Generated by Django 5.2.7 on 2025-10-13 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="institution",
            options={"managed": True},
        ),
        migrations.AlterModelTable(
            name="institution",
            table="instituition",
        ),
    ]
