# Generated by Django 5.2.7 on 2025-10-27 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0003_institution_created_at_institution_updated_at"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="institution",
            table="institution",
        ),
    ]
