# Generated by Django 5.2.7 on 2025-10-27 11:28

import environment
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0005_alter_institution_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="date",
            field=models.DateTimeField(blank=True, default=environment.get_timezone),
        ),
    ]
