# Generated by Django 5.2.7 on 2025-10-27 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0006_alter_institution_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="institution",
            name="date",
        ),
    ]
