# Generated by Django 5.2.7 on 2025-10-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0007_remove_institution_date"),
        ("user", "0004_rename_senha_user_password"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="institution",
            constraint=models.UniqueConstraint(
                fields=("name", "user"), name="unique_institution_user_name"
            ),
        ),
    ]
