# Generated by Django 5.2.7 on 2025-11-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0008_institution_unique_institution_user_name"),
        ("user", "0004_rename_senha_user_password"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="institution",
            name="unique_institution_user_name",
        ),
        migrations.AddConstraint(
            model_name="institution",
            constraint=models.UniqueConstraint(
                fields=("name", "user"), name="unique_institution_name"
            ),
        ),
    ]
