# Generated by Django 5.2.7 on 2025-11-03 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discipline", "0002_discipline_created_at_discipline_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="discipline",
            old_name="curso",
            new_name="course",
        ),
    ]
