# Generated by Django 5.2.7 on 2025-11-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0007_remove_course_unique_course_institution_and_more"),
        ("discipline", "0003_rename_curso_discipline_course"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="discipline",
            constraint=models.UniqueConstraint(
                fields=("name", "course"), name="unique_discipline_name"
            ),
        ),
    ]
