# Generated by Django 5.2.7 on 2025-11-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discipline", "0005_discipline_final_grade_discipline_final_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="discipline",
            name="semester",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
