# Generated by Django 5.2.7 on 2025-11-04 12:14

import django.db.models.deletion
import environment
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discipline", "0006_discipline_semester"),
    ]

    operations = [
        migrations.AddField(
            model_name="discipline",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("WAITING", "Waiting"),
                    ("AWAITING_PREREQUISITE", "Awaiting Prerequisite"),
                ],
                default="WAITING",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="PrerequisiteDiscipline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=environment.get_timezone),
                ),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "main_discipline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prerequisites",
                        to="discipline.discipline",
                    ),
                ),
                (
                    "prerequisite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="is_prerequisite_for",
                        to="discipline.discipline",
                    ),
                ),
            ],
            options={
                "db_table": "prerequisite_discipline",
                "managed": True,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("main_discipline", "prerequisite"),
                        name="unique_discipline_prerequisite",
                    )
                ],
            },
        ),
    ]
